[package]
name = "britt-marie"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

[dependencies]
bloom-filter-rs = "0.1.0"
fxhash = "0.2.1"
cfg-if = "0.1.10"
packed_simd = { version = "0.3.3", optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ['real_blackbox'] }
once_cell = "1.3.1"
rand = "0.7.3"

[features]
default = []
nightly = ["packed_simd"]

[[bench]]
name = "ops"
harness = false

[[bench]]
name = "search"
harness = false

[[bench]]
name = "simd_ops"
harness = false
