[package]
name = "britt-marie"
version = "0.1.0"
authors = ["Max Meldrum <max@meldrum.se>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
cfg-if = "0.1.10"

[dev-dependencies]
criterion = { version = "0.3", features = ['real_blackbox'] }
rand = "0.7.3"

[[bench]]
name = "hash"
harness = false

